#!/bin/bash

clear

COMMAND=sudo python3 src/knn_classifier.py hhd_dataset

case "$OSTYPE" in
    solaris*) echo "THere is not a command for Solaris" ;;
    darwin*)  COMMAND ;;
    linux*)   COMMAND ;;
    bsd*)     echo "There is not information for BSD" ;;
    msys*)    python src\\main.py hhd_dataset ;;
    cygwin*)  echo "There is not information for CYGWIN" ;;
    *)        echo "The OS does not exist!" ;;
esac
